# Generated by Django 4.2.1 on 2023-05-11 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="track",
            field=models.CharField(
                choices=[
                    ("Design", "Design"),
                    ("FrontEnd", "FrontEnd"),
                    ("BackEnd", "BackEnd"),
                    ("Mobile", "Mobile"),
                ],
                default="Design",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(65),
                ],
            ),
        ),
    ]
