# Generated by Django 4.2.1 on 2023-05-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("accounts", "0002_student_track_alter_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
            ),
        ),
    ]
