# Generated by Django 4.2.1 on 2023-05-14 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_student_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="first_Name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="last_Name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="middle_Name",
            new_name="middle_name",
        ),
        migrations.AlterField(
            model_name="student",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
