# Generated by Django 4.2.1 on 2023-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_first_name_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="employment_status",
            field=models.CharField(
                choices=[("Employed", "Employed"), ("Unemployed", "Unemployed")],
                default="Unemployed",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
