# Generated by Django 4.2.1 on 2023-05-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userchoices_mentor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentor",
            options={
                "permissions": (
                    ("can_manage_all_users", "To manage all students and mentors"),
                )
            },
        ),
    ]
