# Generated by Django 4.2.1 on 2023-05-15 18:22

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_mentor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(65),
                    django.core.validators.MinValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="experience",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(60),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
