# Generated by Django 4.2.1 on 2023-05-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_phone_alter_mentor_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mentor",
            old_name="user",
            new_name="username",
        ),
    ]
