# Generated by Django 4.2.1 on 2023-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_user_mentor_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
