# Generated by Django 4.2.1 on 2023-05-16 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("accounts", "0010_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserChoices",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="age",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="country",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="first_Name",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="last_Name",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="middle_Name",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="state",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="track",
        ),
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
        migrations.RemoveField(
            model_name="student",
            name="country",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="state",
        ),
        migrations.RemoveField(
            model_name="student",
            name="track",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(65),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                default="Male",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="country",
                chained_model_field="country",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="track",
            field=models.CharField(
                choices=[
                    ("Design", "Design"),
                    ("FrontEnd", "FrontEnd"),
                    ("BackEnd", "BackEnd"),
                    ("Mobile", "Mobile"),
                ],
                default="BackEnd",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
