# Generated by Django 4.2.1 on 2023-05-16 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_delete_userchoices_remove_mentor_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(65),
                    django.core.validators.MinValueValidator(10),
                ],
            ),
        ),
    ]
