# Generated by Django 4.2.1 on 2023-05-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Select a gender"),
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="track",
            field=models.CharField(
                choices=[
                    ("", "Select a track"),
                    ("Design", "Design"),
                    ("FrontEnd", "FrontEnd"),
                    ("BackEnd", "BackEnd"),
                    ("Mobile", "Mobile"),
                ],
                max_length=100,
            ),
        ),
    ]
