# Generated by Django 4.2.1 on 2023-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_gender_alter_customuser_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pictures",
            field=models.ImageField(default="NULL", upload_to=""),
            preserve_default=False,
        ),
    ]
