# Generated by Django 4.2.1 on 2023-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pictures",
            field=models.ImageField(upload_to="media"),
        ),
    ]
