# Generated by Django 4.2.1 on 2023-06-09 02:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_customuser_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pictures",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
