# Generated by Django 4.2.1 on 2023-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_customuser_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pictures",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
