# Generated by Django 4.2.1 on 2023-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_customuser_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
