# Generated by Django 4.2.1 on 2023-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pictures",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar_ajfzht.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
