# Generated by Django 4.2.1 on 2023-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_customuser_pictures"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="github",
            field=models.URLField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="linkedin",
            field=models.URLField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
