# Generated by Django 4.1 on 2023-08-15 07:48

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_student_github_student_linkedin_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                length=8,
                max_length=16,
                prefix="LMS",
                unique=True,
            ),
        ),
    ]
