# Generated by Django 4.1 on 2023-08-15 07:53

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="api_key",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=22, max_length=22, prefix=""
            ),
        ),
    ]
