# Generated by Django 4.1 on 2023-08-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_rename_student_id_student_studen_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studen_id",
            new_name="student_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="api_key",
        ),
    ]
