# Generated by Django 4.1 on 2023-08-15 08:04

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_rename_studen_id_student_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=8, max_length=16, prefix="LMS", unique=True
            ),
        ),
    ]
