# Generated by Django 4.1 on 2023-08-15 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(65),
                    django.core.validators.MinValueValidator(10),
                ]
            ),
        ),
    ]
