# Generated by Django 4.2.1 on 2023-05-16 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_article_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="log_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
