# Generated by Django 4.2.1 on 2023-05-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_article_log_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="log_time",
        ),
    ]
