# Generated by Django 4.2.1 on 2023-05-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_age"),
        ("content", "0005_tasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
