# Generated by Django 4.2.1 on 2023-05-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_age"),
        ("content", "0006_rename_tasks_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="audience",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Design", "Design"),
                    ("FrontEnd", "FrontEnd"),
                    ("BackEnd", "BackEnd"),
                    ("Mobile", "Mobile"),
                ],
                default="General",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Design", "Design"),
                            ("FrontEnd", "FrontEnd"),
                            ("BackEnd", "BackEnd"),
                            ("Mobile", "Mobile"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
                (
                    "submitted_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(to="content.tag"),
        ),
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(to="content.tag"),
        ),
    ]
