# Generated by Django 4.2.1 on 2023-05-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_audience_tag_task_audience_submission_article_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="audience_2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TEST",
                to="content.task",
            ),
            preserve_default=False,
        ),
    ]
