# Generated by Django 4.2.1 on 2023-05-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_remove_submission_audience_2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="post",
            new_name="task",
        ),
    ]
