# Generated by Django 4.2.1 on 2023-05-18 07:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_rename_post_task_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                error_messages={"invalid": "Deadline cannot be earlier than now!"},
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 18, 7, 13, 53, 507553, tzinfo=datetime.timezone.utc
                        )
                    )
                ],
            ),
        ),
    ]
