# Generated by Django 4.2.1 on 2023-05-23 17:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_gender_alter_customuser_track"),
        ("content", "0011_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="date",
            new_name="submission_date",
        ),
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.mentor",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023,
                            5,
                            23,
                            17,
                            47,
                            28,
                            556626,
                            tzinfo=datetime.timezone.utc,
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
