# Generated by Django 4.2.1 on 2023-05-23 17:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_rename_date_submission_submission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023,
                            5,
                            23,
                            17,
                            49,
                            53,
                            869511,
                            tzinfo=datetime.timezone.utc,
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
