# Generated by Django 4.2.1 on 2023-05-23 20:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_submission_score_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 23, 20, 9, 29, 12203, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
