# Generated by Django 4.2.1 on 2023-05-24 11:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submission_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 24, 11, 40, 5, 467911, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
