# Generated by Django 4.2.1 on 2023-05-24 13:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_submission_submission_status_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="submission_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023,
                            5,
                            24,
                            13,
                            38,
                            55,
                            164782,
                            tzinfo=datetime.timezone.utc,
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
