# Generated by Django 4.2.1 on 2023-05-24 16:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_alter_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="submission_status",
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_status",
            field=models.CharField(
                choices=[("Sumitted", "Submitted"), ("Not Sumitted", "Not Submitted")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023,
                            5,
                            24,
                            16,
                            44,
                            39,
                            387369,
                            tzinfo=datetime.timezone.utc,
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
