# Generated by Django 4.2.1 on 2023-05-25 08:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submitted_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 25, 8, 13, 28, 721459, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
