# Generated by Django 4.2.1 on 2023-05-26 16:30

import datetime
import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_alter_submission_submitted_for_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="post",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Not Submitted", "Not Submitted"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 26, 16, 30, 40, 87500, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
