# Generated by Django 4.2.1 on 2023-05-26 18:41

import datetime
import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_alter_article_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023,
                            5,
                            26,
                            18,
                            41,
                            21,
                            919777,
                            tzinfo=datetime.timezone.utc,
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
