# Generated by Django 4.2.1 on 2023-05-30 04:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_alter_submission_score_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Categories"),
                    ("Announcement", "Announcement"),
                    ("Class", "Class"),
                ],
                default="Class",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2023, 5, 30, 4, 30, 47, 128786, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
