# Generated by Django 4.1 on 2024-03-17 12:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0053_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2024, 3, 17, 12, 5, 45, 827124, tzinfo=datetime.timezone.utc
                        ),
                        message="Deadline cannot be earlier than now!",
                    )
                ]
            ),
        ),
    ]
